### PR TITLE
Fix bounding box on blastable wall

### LINKED ISSUE #69: Bombable walls have a greater hitbox than other walls
You can get stuck on a bombable wall if  you walk along the wall

Reproduction steps:
Find a bombable wall
Move and touch a wall close to bombable wall tile, but not on it
Move towards the bombable wall
Player will get stuck from moving along the wall.

ScreenRecording2019-11-11at10283

### PR DESCRIPTION
**Pull request by rmgr**
Fix #69

### CODE REVIEW

File: tiled/objects.tsx [hunk 1]
```diff
@@ -32,7 +32,7 @@
   </properties>
   <image width="16" height="16" source="images/objects/pressure_plate.png"/>
  </tile>
- <tile id="6">
+ <tile id="6">https://github.com/rmgr/TetraForce.git
```
Comment (marcJV) [inline tiled/objects.tsx]: is this a typo?

Comment (rmgr) [reply tiled/objects.tsx]: My laptop has this rad feature under debian where if you so much as look at the middle click button too hard it dumps your clipboard where ever you're working. I have no idea why I had objects.tsx open though.. Good catch! I'll update the branch when I get a minute today.

Comment (rmgr) [reply tiled/objects.tsx]: Sorted now
